Ingest users, groups and computers
JupiterOne/graph-microsoft-active-directory pull request #5
Opened 2022-04-19 16:40 UTC by neurovelho

# Description

This is the initial integration for Microsoft Active Directory, adding ingestion for users, groups and devices. It works by directly interfacing with the LDAP protocol of the target Active Directory server.

**Note:** Since we're using the LDAP protocol directory it is not possible to record requests and replay them in the test environment. My idea was originally to use an in-memory LDAP server to test against. However, that turned out to be too complex: the in-memory library I was using was not directly compatible with AD. For this reason, I've decided to instead use unit testing and load test data directly from json files (see e.g. src/steps/access/\_\_testdata\_\_ directory).

## Summary

Adds ingestion for users, groups and devices.

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## Checklist

### General Development Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [x] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [ ] My changes properly paginate the target service provider's API
- [ ] My changes properly handle rate limiting of the target service provider's
      API
- [x] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [x] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [x] I have updated the `CHANGELOG.md` file to describe my changes
- [ ] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2022-04-19 20:13 UTC, adam-in-ict commented on src/steps/access/index.ts
> +        typeof user.memberOf === 'string' ? [user.memberOf] : user.memberOf;
The `memberOf` values will just show direct membership, correct?

I think to get the full picture of user membership we need one additional step that builds relationships between groups.  Since ActiveDirectory allows nested groups, users in larger organizations can often have membership to a group through another group.  For example (Group A)-[HAS]->(Group B)->[HAS]->(User 1).  I believe User 1 will be listed as only a member to Group B, but in reality it will actually have access to whatever permissions/access/etc that both groups A and B are granted.

I'd propose a new `buildGroupHasGroupRelationships` function in this file that builds a Group->Group relationship using the `member` array in the group data.

2022-04-20 14:55 UTC, eXtremeX requested changes
Hey @neurovelho, looks great! :rocket: Please see the comments and Adam's suggestion regarding `memberOf`.

2022-04-20 14:55 UTC, eXtremeX commented on src/steps/access/converter.ts
> +        active: true,
Not sure how critical this is for the initial integration, but here are some thoughts:

1) If you wrap the _key with `ad_user:${user.id}` it would look similar to the other integrations. You also did it for "ad_account".

2) The users also have a `description` field, it could be added here.

3) Another interesting topic are the timestamps (whenCreated, whenChanged, there are also a few regarding log on/off events). Integrations generally use [createdOn](https://github.com/search?q=org%3AJupiterOne+createdOn&type=code) / [updatedOn](https://github.com/search?q=org%3AJupiterOne+updatedOn&type=code) whenever possible. There are also util functions to parse that into common time data type used throughout these integrations.

2022-04-20 14:55 UTC, eXtremeX commented on src/steps/access/converter.ts
> +  });
Similar to above:

1) If you wrap the _key with `ad_group:${group.id}` it would look similar to the other integrations.

2) The groups also have a `description` and `name` fields, I would add them both. There is also `groupType` field, but the value doesn't seem super approachable, perhaps in the future if we have a need to do that it might be parsed some way.

3) Another interesting topic are the timestamps (whenCreated, whenChanged, there are also a few regarding log on/off events). Integrations generally use [createdOn](https://github.com/search?q=org%3AJupiterOne+createdOn&type=code) / [updatedOn](https://github.com/search?q=org%3AJupiterOne+updatedOn&type=code) whenever possible. There are also util functions to parse that into common time data type used throughout these integrations.

2022-04-20 14:55 UTC, eXtremeX commented on src/steps/access/converter.ts
> +        operatingSystemVersion: computer.operatingSystemVersion,
Very similar to the previous comments, the _key and the timestamps could be of interest.

2022-04-25 13:04 UTC, adam-in-ict commented on src/steps/access/index.ts
> +        typeof user.memberOf === 'string' ? [user.memberOf] : user.memberOf;
Sounds good!  Thanks!  I'm happy to approve once you and @eXtremeX are happy with the PR.

2022-04-25 13:31 UTC, eXtremeX approved these changes

2022-04-25 13:33 UTC, eXtremeX commented on src/steps/access/index.ts
> +        typeof user.memberOf === 'string' ? [user.memberOf] : user.memberOf;
Hey @adam-in-ict please approve it when you can!

2022-04-25 13:36 UTC, adam-in-ict approved these changes

2022-04-25 13:37 UTC, merged

2023-07-26 23:19 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v3.2.0`](https://github.com/JupiterOne/graph-microsoft-active-directory/releases/tag/v3.2.0) :rocket: